[features]
seeds = false
skip-lint = false

[programs.localnet]
rpg = "2jqUJr2sQzfNhzpTEnUnMbM2enCs4kQG6YTjmm1SZ9rN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
